# fly.toml app configuration file generated for customer-account-verification on 2023-09-23T14:01:33+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# https://customer-account-verification.fly.dev/customerdashboard/post-customer-data

app = "customer-account-verification"
primary_region = "maa"

[env]
  PORT = "3000"
  SHOPIFY_APP_URL = "https://customer-account-verification.fly.dev"
  SHOPIFY_API_KEY = "fe04d82cbf1ba0a5aa5ec702f06dd73d"
  SHOPIFY_API_SECRET="8fae4ac0f7a0e9766af65194b7ca3f03"
  SCOPES = "read_customers,read_locales,write_customers,read_themes,write_themes"



[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
