# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "20384d45f5b73f1e1a6c806428ab773d"
application_url = "https://finnish-beer-yellow-bristol.trycloudflare.com"
embedded = true
name = "EmailCheckr: Activation<REMIX>"
handle = "email-checkr"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/shop_redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_locales,read_themes,write_customers,write_themes"

[auth]
redirect_urls = [
  "https://finnish-beer-yellow-bristol.trycloudflare.com/auth/callback",
  "https://finnish-beer-yellow-bristol.trycloudflare.com/auth/shopify/callback",
  "https://finnish-beer-yellow-bristol.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://finnish-beer-yellow-bristol.trycloudflare.com/app/post-api"
subpath = "verification"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "silver-heritage-heaven.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
